fixed the dockerfiles for all pwn challenges

diff --git a/pwn/printf1/src/Dockerfile b/pwn/printf1/src/Dockerfile
--- a/pwn/printf1/src/Dockerfile
+++ b/pwn/printf1/src/Dockerfile
@@ -5,14 +5,15 @@ RUN apt-get update
 RUN apt-get install -y gcc make
 
 # setup challenge
-ARG USERNAME=magpie
-RUN useradd -m $USERNAME
-RUN chmod a-w /home/$USERNAME
-RUN chmod o+x /home/$USERNAME
+RUN groupadd -g 1001 magpie
+RUN useradd -u 1001 magpie -g magpie
+RUN mkdir /ctf
+RUN chmod a-w /ctf
+RUN chmod o+x /ctf
 
 # building the challenge in the container
-# the || true is for steps that might fail
-WORKDIR /home/$USERNAME
+# the `|| true` is for steps that might fail
+WORKDIR /ctf
 COPY . ./
 RUN make clean || true
 RUN make
@@ -20,7 +21,7 @@ RUN rm Makefile *.c
 
 EXPOSE 6201
 
-CMD ["bin/nsjail", \
+CMD ["/bin/nsjail", \
     "-Ml", \
     "--hostname", "localhost", \
     "--port", "6201", \
@@ -28,6 +29,6 @@ CMD ["bin/nsjail", \
     "--group", "1001", \
     "--chroot", "/", \
     "-E", "TERM=xterm", \
-    "--cwd", "/home/$USERNAME", \
+    "--cwd", "/ctf", \
     "--", \
-    "/home/$USERNAME/printf1"]
+    "/ctf/printf1"]
